name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Download dependencies
        run: go mod download

      - name: Lint go files
        uses: golangci/golangci-lint-action@v3
        with:
          skip-cache: true